### PR TITLE
feat : added rating slider modal and list components

### PR DESCRIPTION
**Pull request by BalajiHarinath**
added rating slider modal and list components to the CL. Please review.

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me!

**Review by anik31 — APPROVED** [review]
Everything looks good. suggestion - decrease the height of header of your CL & align the items

**Review by hsnice16 — APPROVED** [review]
Great work, man. Nice color choice and nice used it to show the components. The code looks good too.

**Comment by BalajiHarinath** [comment]
> Everything looks good. suggestion - decrease the height of header of your CL & align the items

Sure will do it. Thanks for suggesting this.

**Comment by BalajiHarinath** [comment]
> > Everything looks good. suggestion - decrease the height of header of your CL & align the items
> 
> Sure will do it. Thanks for suggesting this.

I have reduced the height of the nav bar and aligned the items of the nav bar as well.

**Pull request merged**
